import Head from "next/head";
import {
  Container,
  Heading,
  Table,
  Td,
  Th,
  Tr,
  Thead,
  Tbody,
  Spinner,
  Box,
  Text,
} from "@chakra-ui/react";
import { useQuery } from "@tanstack/react-query";
import { axiosIstance } from "@/lib/axios";

export default function Home() {
  const { data, isLoading, isError, error } = useQuery({
    queryKey: ["repoData"],
    queryFn: async () => {
      const productResponse = await axiosIstance.get("/products");
      return productResponse.data; // Return data property
    },
  });

  const renderProducts = () => {
    return data?.map((product) => (
      <Tr key={product.id}>
        <Td>{product.id}</Td>
        <Td>{product.name}</Td>
        <Td>{product.price}</Td>
        <Td>{product.description}</Td>
        <Td>{product.image}</Td>
      </Tr>
    ));
  };

  if (isError) return <Text>An error has occurred: {error.message}</Text>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading>Hello World</Heading>
          {isLoading ? (
            <Box textAlign="center">
              <Spinner size="xl" />
            </Box>
          ) : (
            <Table>
              <Thead>
                <Tr>
                  <Th>ID</Th>
                  <Th>Name</Th>
                  <Th>Price</Th>
                  <Th>Description</Th>
                  <Th>Image</Th>
                </Tr>
              </Thead>
              <Tbody>{renderProducts()}</Tbody>
            </Table>
          )}
        </Container>
      </main>
    </>
  );
}
