import Head from "next/head";
import {
  Container,
  Heading,
  Table,
  Td,
  Th,
  Tr,
  Thead,
  Tbody,
} from "@chakra-ui/react";
import { useEffect, useState } from "react";
import { axiosIstance } from "@/lib/axios";

export default function Home() {
  const [products, setProducts] = useState([]);

  const fetchProducts = async (req, res) => {
    try {
      const productResponse = await axiosIstance.get("/products");
      setProducts(productResponse.data);
    } catch (error) {
      console.error(error);
    }
  };

  const renderProducts = () => {
    return products.map((product) => {
      return (
        <Tr key={product.id}>
          <Td>{product.id}</Td>
          <Td>{product.name}</Td>
          <Td>{product.price}</Td>
          <Td>{product.description}</Td>
          <Td>{product.image}</Td>
        </Tr>
      );
    });
  };

  useEffect(() => {
    fetchProducts();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading>Hello World</Heading>
          <Table>
            <Thead>
              <Tr>
                <Th>ID</Th>
                <Th>Name</Th>
                <Th>Price</Th>
                <Th>Description</Th>
                <Th>image</Th>
              </Tr>
            </Thead>
            <Tbody>{renderProducts()}</Tbody>
          </Table>
        </Container>
      </main>
    </>
  );
}
